<?php


/**
 * Adds the jQuery jstree plugin to a page.
 * @deprecated
 *   Use drupal_add_library('jquery_jstree', 'jstree')
 */
function jquery_jstree_plugin_add() {
  drupal_add_library('jquery_jstree', 'jstree');
}

/*
 * Implements hook_library().
 */
function jquery_jstree_library() {
  $libraries = libraries_get_libraries();
  if (empty($libraries['jstree']) || !file_exists($libraries['jstree'] . '/jquery.jstree.js')) {
    drupal_set_message('Cannot find jsTree library directory.', 'error');
    return array();
  }
  return array(
    'jstree' => array(
      'title' => 'jsTree',
      'website' => 'http://www.jstree.com/',
      'version' => 'pre1.0',
      'js' => array(
        $libraries['jstree'] . '/jquery.jstree.js' => array(),
      ),
    )
  );
}

/**
 * Implements hook_theme().
 */
function jquery_jstree_theme() {
  return array(
    'jstree' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_element_info().
 *
 * @TODO jsTree as input element
 */
function jquery_jstree_element_info() {
  $types['jstree'] = array(
    '#theme' => 'jstree',
    '#pre_render' => array('jquery_jstree_element_pre_render'),
    '#attached' => array(
      // jsTree library
      'library' => array(array('jquery_jstree', 'jstree')),
      // Drupal behavior to initialize the tree.
      'js' => array(drupal_get_path('module', 'jquery_jstree') . '/jquery_jstree.js')
    ),
    '#attributes' => array(),
    '#options' => array(),
// @TODO jsTree as input element
//    '#input' => FALSE,
//    '#process' => array('jquery_jstree_element_process'),
//    '#element_validate' => array('jquery_jstree_element_validate'),
  );
  return $types;
}

/**
 * Pre-render callback for jsTree element.
 *
 * @param array $element
 *  The rendered jsTree element.
 */
function jquery_jstree_element_pre_render($element) {
  // Ensure ID
  if (empty($element['#attributes']['id'])) {
    $element['#attributes']['id'] = drupal_html_id('jstree');
  }
  // Ensure plugins options is an array
  if (empty($element['#options']['plugins']) || !is_array($element['#options']['plugins'])) {
    $element['#options']['plugins'] = empty($element['#options']['plugins']) ? array() : array($element['#options']['plugins']);
  }
  // Attach JavaScript settings, used by our behavior to initialize the tree.
  $element['#attached']['js'][] = array(
    'type' => 'setting',
    'data' => array('jstree' => array($element['#attributes']['id'] => $element['#options']))
  );
  return $element;
}

/**
 * Default theme function for jsTree element.
 *
 * @param array $variables
 */
function theme_jstree($variables) {
  $element =& $variables['element'];
  return '<div ' . drupal_attributes($element['#attributes']) . '>' . drupal_render_children($element) . '</div>';
}

/**
 * Form process callback for jsTree element.
 *
 * @TODO jsTree as input element
 *
 * @param array $element
 * @param array $form_state
 * @param array $complete_form
 */
//function jquery_jstree_element_process($element, &$form_state, $complete_form) {
//
//}

/**
 * Validation callback for jsTree element.
 *
 * @TODO jsTree as input element
 *
 * @param array $element
 * @param array $form_state
 */
//function jquery_jstree_element_validate($element, &$form_state) {
//
//}

/**
 * Value callback for jsTree element.
 *
 * @TODO jsTree as input element
 *
 * @param array $element
 * @param array $input
 * @param array $form_state
 */
//function form_type_jstree_value(&$element, $input = FALSE, $form_state = NULL) {
//
//}